name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: mkdir toolchains
    - name: NDK
      uses: ravinderjangra/android-ndk-toolchain-setup@0.1
      with:
        api: '21'
        arch: 'x86'
        install-location: 'toolchains'
        force: true
